version: 1.0
deployment:
  bootstrap:
    post-deployment-remote-commands:
      - mkdir -p $HOME/.deploy-now/uploads/models $HOME/.deploy-now/uploads/catalog
      - ln -sfn $HOME/.deploy-now/uploads $HOME/uploads
      - php8.5-cli $HOME/setup.php
  recurring:
    post-deployment-remote-commands:
      - mkdir -p $HOME/.deploy-now/uploads/models $HOME/.deploy-now/uploads/catalog
      - ln -sfn $HOME/.deploy-now/uploads $HOME/uploads
      - php8.5-cli $HOME/setup.php
